name: color_canvas
description: "Unleash your inner interior designer with \"Paint Roller,\" the mobile-first app that transforms how you discover and visualize paint palettes, featuring real colors from leading brands like Sherwin-Williams, Benjamin Moore, and Behr."
publish_to: "none"
version: 1.0.0

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  cloud_firestore: ^6.0.0
  firebase_core: ^4.0.0
  firebase_auth: ^6.0.1
  firebase_app_check: ^0.4.0
  firebase_data_connect: ^0.2.0+1
  cloud_functions: ^6.0.0
  firebase_storage: ^13.0.0
  firebase_ai: any
  firebase_analytics: ^12.0.0
  firebase_analytics_web: ^0.6.0
  connectivity_plus: ^6.0.3
  cached_network_image: ^3.4.1
  hive: ^2.2.3
  firebase_messaging: ^16.0.0
  flutter_local_notifications: ^19.4.1
  just_audio: ^0.10.4
  share_plus: ^11.1.0
  firebase_crashlytics: ^5.0.0
  package_info_plus: ^8.0.0
  collection: ^1.18.0
  logging: ^1.2.0
  cupertino_icons: ^1.0.8
  google_fonts: ^6.1.0
  shared_preferences: ^2.0.0
  flutter_svg: ^2.0.0
  image: ^4.3.0
  path_provider: ^2.0.0
  flutter_colorpicker: ^1.0.0
  file_picker: '>=8.1.2'
  pdf: ^3.10.8
  printing: ^5.12.0
  screenshot: ^3.0.0
  image_picker: '>=1.1.2'
  permission_handler: ^12.0.1
  http: ^1.1.0
  # UI helpers
  photo_view: ^0.15.0
  sqflite: ^2.4.2
  url_launcher: ^6.3.0
  firebase_remote_config: ^6.0.0
  timezone: ^0.10.1
  webview_flutter: ^4.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0



dependency_overrides:
  sqflite_android: 2.4.0-1

flutter:
  uses-material-design: true
  assets:
    - assets/documents/